name: Test-create and publish Docker images

on:
  push:
    paths:
      - Dockerfile
      - data.Dockerfile
      - .github/workflows/containers.yaml

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push regular image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/jj/ukr-mod-data-csv

      - name: Build and push data image
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: data.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/jj/ukr-mod-data

