name: "Scrape downloaded HTML when created"
on:
  push:
    paths:
      - 'raw-pages/*.html'
      - ".github/workflows/generate-new-CSV.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate CSV
        run: docker run -t -v `pwd`:$GITHUB_HOME/test ghcr.io/jj/ukr-mod-data:latest
      - name: Check in if there are changes
        run: |
          if [ -n "$(git status -s)" ]; then
              bin/commit-push.sh "Re-generates CSV"
              git push
          else
              echo "ℹ No changes in CSV"
          fi
