name: "Scrape downloaded HTML when created"
on:
  push:
    paths:
      - 'raw-pages/*.html'
      - ".github/workflows/generate-new-CSV.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/jj/raku-zef-gha
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache installed dists
        uses: actions/cache@v2
        id: meta6
        with:
          path: ~/.raku/
          key: ${{ runner.os }}-${{ hashFiles('META6.json') }}
      - name: Install modules
        if: steps.meta6.outputs.cache-hit != 'true'
        run: zef install .
      - name: Generate CSV
        run: ake CSV
      - name: Check in if there are changes
        run: |
          ls /bin/
          if [ -n "$(git status -s)" ]; then
              bin/commit-push.sh "Re-generates CSV"
              git push
          else
              echo "ℹ No changes in CSV"
          fi
