name: "Scrape downloaded HTML when created and generate CSV"
on:
  push:
    paths:
      - 'raw-pages/*.html'
      - '.github/workflows/generate-new-CSV.yaml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate CSV using containerized script
        run: docker run -t -v `pwd`:/home/raku/test ghcr.io/jj/ukr-mod-data:latest
      - name: Check in if there are changes
        run: |
          if [ -n "$(git status -s)" ]; then
              tools/commit-push.sh "Re-generates CSV"
              git push
          else
              echo "ℹ No changes in CSV"
          fi
