name: "Generates parquet from the CSV file"
on:
  push:
    paths:
      - "resources/*.csv"
      - ".github/workflows/parquet.yml"

jobs:
  generate_parquet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"
      - name: Install CSV to Parquet cli tool
        run: go install github.com/fraugster/parquet-go/cmd/csv2parquet@latest
      - name: Convert CSV to Parquet
        working-directory: resources
        run: csv2parquet -input ukr-mod-data.csv -output ukr-mod-data.parquet
      - name: Check in
        run: |
          git config --global user.email 'jjmerelo@gmail.com'
          git config --global user.name "UKR-Mod-Data repo"
          export DATE=$(date +"%y-%m-%d")
          git commit -am "Re-generated parquet file for $(DATE)"
          git tag -a v$DATE -m "Tagging data for $(date)"
          git push --follow tags
