name: "Generates parquet from the CSV file"
on:
  push:
    paths:
      - "resources/*.csv"
      - ".github/workflows/parquet.yml"

  schedule:
    - cron: '31 23 * * *'

jobs:
  generate_parquet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.18.3"
      - name: Install CSV to Parquet cli tool
        run: go install github.com/fraugster/parquet-go/cmd/csv2parquet@latest
      - name: Convert CSV to Parquet
        working-directory: resources
        run: csv2parquet -input ukr-mod-data.csv -output ukr-mod-data.parquet
      - name: Check in
        run: |
          if [ -n "$(git status -s)" ]; then
              export DATE=$(date +"%y-%m-%d")
              tools/commit-push.sh "Re-generated parquet file for $DATE"
              git tag -a data-$DATE -m "Tagging data for $(date)"
              git push --follow-tags
          else
              echo "ℹ No changes in CSV"
          fi
