name: "Generate charts directly"

on:
  push:
    paths:
      - "resources/ukr_mod_data.csv"
      - ".github/workflows/R-stuff.yml"
      - "bin/plot-pairs.R"

jobs:
  MDSpelling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::GGally
            any::reshape2
          needs: check
      - name: Generate chart
        run: Rscript bin/plot-pairs.R
      - name: Check in result
        run: |
          if [ -n "$(git status -s)" ]; then
              export DATE=$(date +"%y-%m-%d")
              bin/commit-push.sh "Re-generated CSV split files for $DATE"
              git tag -a data-shaped-$DATE -m "Tagging data for $(date)"
              git push --follow-tags
          else
              echo "ℹ No changes in CSV"
          fi
