name: "Generate charts, deltas and packaged"

on:
  push:
    paths:
      - "resources/*.csv"
      - ".github/workflows/R-stuff.yml"
      - "tools/plot-pairs.R"
      - "DESCRIPTION"

jobs:
  generate-charts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          needs: check
      - name: Generate chart
        run: Rscript tools/plot-pairs.R
      - name: Check in result
        run: |
          if [ -n "$(git status -s)" ]; then
              export DATE=$(date +"%y-%m-%d")
              tools/commit-push.sh "Re-generated CSV split files for $DATE"
              git tag -a data-shaped-$DATE -m "Tagging data for $(date)"
              git push --follow-tags
          else
              echo "ℹ No changes in CSV"
          fi
